import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

import '../domain/device.dart';
import '../domain/enums.dart';
import '../domain/ids.dart';
import '../support/json_utils.dart';

/// Challenge payload generated by the phone hub for QR-based pairing.
@immutable
class DevicePairingSession extends Equatable {
  final PairingSessionId id;
  final DeviceId hubDeviceId;
  final DeviceRole requestedRole;
  final PairingStatus status;
  final String qrSecret;
  final List<String> requestedCapabilities;
  final DateTime createdAt;
  final DateTime expiresAt;
  final DateTime? decidedAt;

  const DevicePairingSession({
    required this.id,
    required this.hubDeviceId,
    required this.requestedRole,
    required this.status,
    required this.qrSecret,
    required this.createdAt,
    required this.expiresAt,
    this.requestedCapabilities = const [],
    this.decidedAt,
  });

  Map<String, dynamic> toJson() => {
        'id': id.value,
        'hubDeviceId': hubDeviceId.value,
        'requestedRole': requestedRole.name,
        'status': status.name,
        'qrSecret': qrSecret,
        'requestedCapabilities': requestedCapabilities,
        'createdAt': createdAt.toIso8601String(),
        'expiresAt': expiresAt.toIso8601String(),
        'decidedAt': decidedAt?.toIso8601String(),
      };

  factory DevicePairingSession.fromJson(Map<String, dynamic> json) =>
      DevicePairingSession(
        id: PairingSessionId.fromJson(json['id']),
        hubDeviceId: DeviceId.fromJson(json['hubDeviceId']),
        requestedRole: enumByName(DeviceRole.values, json['requestedRole']),
        status: enumByName(PairingStatus.values, json['status']),
        qrSecret: json['qrSecret'] as String,
        requestedCapabilities:
            castJsonList(json['requestedCapabilities']).cast<String>(),
        createdAt: parseDateTime(json['createdAt']),
        expiresAt: parseDateTime(json['expiresAt']),
        decidedAt: parseNullableDateTime(json['decidedAt']),
      );

  @override
  List<Object?> get props => [
        id,
        hubDeviceId,
        requestedRole,
        status,
        qrSecret,
        requestedCapabilities,
        createdAt,
        expiresAt,
        decidedAt,
      ];
}

/// Trusted companion response for completing the pairing handshake.
@immutable
class DevicePairingResponse extends Equatable {
  final PairingSessionId sessionId;
  final Device remoteDevice;
  final bool accepted;
  final DateTime respondedAt;
  final List<String> grantedCapabilities;
  final String? denialReason;

  const DevicePairingResponse({
    required this.sessionId,
    required this.remoteDevice,
    required this.accepted,
    required this.respondedAt,
    this.grantedCapabilities = const [],
    this.denialReason,
  });

  Map<String, dynamic> toJson() => {
        'sessionId': sessionId.value,
        'remoteDevice': remoteDevice.toJson(),
        'accepted': accepted,
        'respondedAt': respondedAt.toIso8601String(),
        'grantedCapabilities': grantedCapabilities,
        'denialReason': denialReason,
      };

  factory DevicePairingResponse.fromJson(Map<String, dynamic> json) =>
      DevicePairingResponse(
        sessionId: PairingSessionId.fromJson(json['sessionId']),
        remoteDevice: Device.fromJson(castJsonMap(json['remoteDevice'])),
        accepted: json['accepted'] as bool,
        respondedAt: parseDateTime(json['respondedAt']),
        grantedCapabilities:
            castJsonList(json['grantedCapabilities']).cast<String>(),
        denialReason: json['denialReason'] as String?,
      );

  @override
  List<Object?> get props => [
        sessionId,
        remoteDevice,
        accepted,
        respondedAt,
        grantedCapabilities,
        denialReason,
      ];
}
